version: '3'
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    network_mode: "host"  # Use host networking
    volumes:
      - ./synapse:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml:ro
      - ./synapse/localhost.log.config:/data/localhost.log.config:ro
    environment:
      SYNAPSE_SERVER_NAME: localhost
      SYNAPSE_REPORT_STATS: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/_matrix/client/versions"]
      interval: 5s
      timeout: 5s
      retries: 5

  custom-auth-provider:
    build: .
    container_name: custom-auth-provider
    network_mode: "host"  # Use host networking
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/.well-known/openid-configuration"]
      interval: 5s
      timeout: 5s
      retries: 5

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    network_mode: "host"  # Use host networking
    environment:
      OAUTH2_PROXY_CLIENT_ID: "123456"
      OAUTH2_PROXY_CLIENT_SECRET: "2c0c5502258bec795333828e3d7548b8"
      OAUTH2_PROXY_COOKIE_SECRET: "2c0c5502258bec795333828e3d7548b8"
      OAUTH2_PROXY_UPSTREAM: http://localhost:8008
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://localhost:5000"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".localhost"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".localhost"
    depends_on:
      - custom-auth-provider